// This file is auto-generated by @hey-api/openapi-ts

/**
 * ActionConfirmationStatus
 */
export type ActionConfirmationStatus = 'confirmed' | 'rejected' | 'awaiting_confirmation';

/**
 * ActionRequest
 * Generic action request that accepts any action type.
 * The validation and conversion is handled by the existing action_from_dict system.
 *
 * This approach reuses the existing action classes from openhands.events.action
 * instead of duplicating type definitions.
 *
 * Supported action types:
 * - run: Execute shell commands (CmdRunAction)
 * - run_ipython: Execute Python code (IPythonRunCellAction)
 * - read: Read files (FileReadAction)
 * - write: Write files (FileWriteAction)
 * - edit: Edit files (FileEditAction)
 * - browse: Browse URLs (BrowseURLAction)
 * - browse_interactive: Interactive browsing (BrowseInteractiveAction)
 * - think: Agent thinking (AgentThinkAction)
 * - finish: Agent completion (AgentFinishAction)
 * - reject: Agent rejection (AgentRejectAction)
 * - message: User messages (MessageAction)
 * - mcp: MCP tool calls (MCPAction)
 * - null: No-op actions (NullAction)
 * - delegate: Agent delegation (AgentDelegateAction)
 * - recall: Memory recall (RecallAction)
 * - condensation: Memory condensation (CondensationAction)
 * - change_agent_state: Change agent state (ChangeAgentStateAction)
 * - system_message: System messages (SystemMessageAction)
 */
export type ActionRequest = {
    /**
     * Action
     * The type of action to perform
     */
    action: string;
    /**
     * Args
     * Arguments for the action. The expected fields depend on the action type:
     * - run: command (str), background (bool), timeout (int), cwd (str), thought (str)
     * - read: path (str), start (int), end (int), view_range (tuple), thought (str)
     * - write: path (str), content (str), start (int), end (int), thought (str)
     * - edit: path (str), old_str (str), new_str (str), insert_line (int), command (str), thought (str)
     * - browse: url (str), thought (str)
     * - browse_interactive: browser_actions (str), thought (str)
     * - think: thought (str)
     * - finish: outputs (dict), thought (str)
     * - message: content (str), image_urls (list), wait_for_response (bool), thought (str)
     * - mcp: tool (str), args (dict), thought (str)
     * And many more... See action classes in openhands.events.action for complete schemas.
     */
    args: NullAction | CmdRunAction | IPythonRunCellAction | BrowseUrlAction | BrowseInteractiveAction | FileReadAction | FileWriteAction | FileEditAction | AgentThinkAction | AgentFinishAction | AgentRejectAction | AgentDelegateAction | RecallAction | ChangeAgentStateAction | MessageAction | SystemMessageAction | CondensationAction | McpAction;
    /**
     * Timeout
     * Timeout for the action in seconds
     */
    timeout?: number | null;
    /**
     * Blocking
     * Whether the action should block
     */
    blocking?: boolean | null;
    [key: string]: unknown | string | (NullAction | CmdRunAction | IPythonRunCellAction | BrowseUrlAction | BrowseInteractiveAction | FileReadAction | FileWriteAction | FileEditAction | AgentThinkAction | AgentFinishAction | AgentRejectAction | AgentDelegateAction | RecallAction | ChangeAgentStateAction | MessageAction | SystemMessageAction | CondensationAction | McpAction) | (number | null) | (boolean | null) | undefined;
};

/**
 * ActionSecurityRisk
 */
export type ActionSecurityRisk = -1 | 0 | 1 | 2;

/**
 * ActionType
 */
export type ActionType = 'message' | 'system' | 'start' | 'read' | 'write' | 'edit' | 'run' | 'run_ipython' | 'browse' | 'browse_interactive' | 'call_tool_mcp' | 'delegate' | 'think' | 'finish' | 'reject' | 'null' | 'pause' | 'resume' | 'stop' | 'change_agent_state' | 'push' | 'send_pr' | 'recall' | 'condensation';

/**
 * AgentDelegateAction
 */
export type AgentDelegateAction = {
    /**
     * Agent
     */
    agent: string;
    /**
     * Inputs
     */
    inputs: {
        [key: string]: unknown;
    };
    /**
     * Thought
     */
    thought?: string;
    /**
     * Action
     */
    action?: string;
};

/**
 * AgentFinishAction
 */
export type AgentFinishAction = {
    /**
     * Final Thought
     */
    final_thought?: string;
    task_completed?: AgentFinishTaskCompleted | null;
    /**
     * Outputs
     */
    outputs?: {
        [key: string]: unknown;
    };
    /**
     * Thought
     */
    thought?: string;
    /**
     * Action
     */
    action?: string;
};

/**
 * AgentFinishTaskCompleted
 */
export type AgentFinishTaskCompleted = 'false' | 'partial' | 'true';

/**
 * AgentRejectAction
 */
export type AgentRejectAction = {
    /**
     * Outputs
     */
    outputs?: {
        [key: string]: unknown;
    };
    /**
     * Thought
     */
    thought?: string;
    /**
     * Action
     */
    action?: string;
};

/**
 * AgentThinkAction
 */
export type AgentThinkAction = {
    /**
     * Thought
     */
    thought?: string;
    /**
     * Action
     */
    action?: string;
};

/**
 * Branch
 */
export type Branch = {
    /**
     * Name
     */
    name: string;
    /**
     * Commit Sha
     */
    commit_sha: string;
    /**
     * Protected
     */
    protected: boolean;
    /**
     * Last Push Date
     */
    last_push_date?: string | null;
};

/**
 * BrowseInteractiveAction
 */
export type BrowseInteractiveAction = {
    /**
     * Browser Actions
     */
    browser_actions: string;
    /**
     * Thought
     */
    thought?: string;
    /**
     * Browsergym Send Msg To User
     */
    browsergym_send_msg_to_user?: string;
    /**
     * Action
     */
    action?: string;
    security_risk?: ActionSecurityRisk | null;
    /**
     * Return Axtree
     */
    return_axtree?: boolean;
};

/**
 * BrowseURLAction
 */
export type BrowseUrlAction = {
    /**
     * Url
     */
    url: string;
    /**
     * Thought
     */
    thought?: string;
    /**
     * Action
     */
    action?: string;
    security_risk?: ActionSecurityRisk | null;
    /**
     * Return Axtree
     */
    return_axtree?: boolean;
};

/**
 * ChangeAgentStateAction
 */
export type ChangeAgentStateAction = {
    /**
     * Agent State
     */
    agent_state: string;
    /**
     * Thought
     */
    thought?: string;
    /**
     * Action
     */
    action?: string;
};

/**
 * CmdRunAction
 */
export type CmdRunAction = {
    /**
     * Command
     */
    command: string;
    /**
     * Is Input
     */
    is_input?: boolean;
    /**
     * Thought
     */
    thought?: string;
    /**
     * Blocking
     */
    blocking?: boolean;
    /**
     * Is Static
     */
    is_static?: boolean;
    /**
     * Cwd
     */
    cwd?: string | null;
    /**
     * Hidden
     */
    hidden?: boolean;
    /**
     * Action
     */
    action?: string;
    confirmation_state?: ActionConfirmationStatus;
    security_risk?: ActionSecurityRisk | null;
};

/**
 * CondensationAction
 */
export type CondensationAction = {
    /**
     * Action
     */
    action?: string;
    /**
     * Forgotten Event Ids
     */
    forgotten_event_ids?: Array<number> | null;
    /**
     * Forgotten Events Start Id
     */
    forgotten_events_start_id?: number | null;
    /**
     * Forgotten Events End Id
     */
    forgotten_events_end_id?: number | null;
    /**
     * Summary
     */
    summary?: string | null;
    /**
     * Summary Offset
     */
    summary_offset?: number | null;
};

/**
 * ConversationInfo
 */
export type ConversationInfo = {
    /**
     * Conversation Id
     */
    conversation_id: string;
    /**
     * Title
     */
    title: string;
    /**
     * Last Updated At
     */
    last_updated_at?: string | null;
    status?: ConversationStatus;
    runtime_status?: RuntimeStatus | null;
    /**
     * Selected Repository
     */
    selected_repository?: string | null;
    /**
     * Selected Branch
     */
    selected_branch?: string | null;
    git_provider?: ProviderType | null;
    trigger?: ConversationTrigger | null;
    /**
     * Num Connections
     */
    num_connections?: number;
    /**
     * Url
     */
    url?: string | null;
    /**
     * Session Api Key
     */
    session_api_key?: string | null;
    /**
     * Created At
     */
    created_at?: string;
};

/**
 * ConversationInfoResultSet
 */
export type ConversationInfoResultSet = {
    /**
     * Results
     */
    results?: Array<ConversationInfo>;
    /**
     * Next Page Id
     */
    next_page_id?: string | null;
};

/**
 * ConversationResponse
 */
export type ConversationResponse = {
    /**
     * Status
     */
    status: string;
    /**
     * Conversation Id
     */
    conversation_id: string;
    /**
     * Message
     */
    message?: string | null;
    conversation_status?: ConversationStatus | null;
};

/**
 * ConversationStatus
 */
export type ConversationStatus = 'STARTING' | 'RUNNING' | 'STOPPED';

/**
 * ConversationTrigger
 */
export type ConversationTrigger = 'resolver' | 'gui' | 'suggested_task' | 'openhands_api' | 'slack';

/**
 * CreateRuntimeSessionRequest
 */
export type CreateRuntimeSessionRequest = {
    /**
     * Session Id
     */
    session_id?: string | null;
};

/**
 * CustomSecretModel
 * Custom secret model with value
 */
export type CustomSecretModelReadable = {
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description?: string | null;
};

/**
 * CustomSecretModel
 * Custom secret model with value
 */
export type CustomSecretModelWritable = {
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Value
     */
    value: string;
};

/**
 * CustomSecretWithoutValueModel
 * Custom secret model without value
 */
export type CustomSecretWithoutValueModel = {
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description?: string | null;
};

/**
 * EventFilter
 */
export type EventFilter = {
    /**
     * Exclude Hidden
     */
    exclude_hidden?: boolean;
    /**
     * Query
     */
    query?: string | null;
    /**
     * Include Types
     */
    include_types?: Array<unknown> | null;
    /**
     * Exclude Types
     */
    exclude_types?: Array<unknown> | null;
    /**
     * Source
     */
    source?: string | null;
    /**
     * Start Date
     */
    start_date?: string | null;
    /**
     * End Date
     */
    end_date?: string | null;
};

/**
 * EventRequest
 * Request model for adding events to the runtime session.
 */
export type EventRequest = {
    /**
     * Action to perform. Must be a valid action type from openhands.events.action
     */
    action?: ActionRequest | null;
    /**
     * Observation
     */
    observation?: string | null;
    /**
     * Content
     */
    content?: string | null;
    /**
     * Message
     */
    message?: string | null;
    /**
     * Source
     */
    source?: string | null;
    /**
     * Timestamp
     */
    timestamp?: string | null;
};

/**
 * FileEditAction
 */
export type FileEditAction = {
    /**
     * Path
     */
    path: string;
    /**
     * Command
     */
    command?: string;
    /**
     * File Text
     */
    file_text?: string | null;
    /**
     * Old Str
     */
    old_str?: string | null;
    /**
     * New Str
     */
    new_str?: string | null;
    /**
     * Insert Line
     */
    insert_line?: number | null;
    /**
     * Content
     */
    content?: string;
    /**
     * Start
     */
    start?: number;
    /**
     * End
     */
    end?: number;
    /**
     * Thought
     */
    thought?: string;
    /**
     * Action
     */
    action?: string;
    security_risk?: ActionSecurityRisk | null;
    impl_source?: FileEditSource;
};

/**
 * FileEditSource
 */
export type FileEditSource = 'llm_based_edit' | 'oh_aci';

/**
 * FileReadAction
 */
export type FileReadAction = {
    /**
     * Path
     */
    path: string;
    /**
     * Start
     */
    start?: number;
    /**
     * End
     */
    end?: number;
    /**
     * Thought
     */
    thought?: string;
    /**
     * Action
     */
    action?: string;
    security_risk?: ActionSecurityRisk | null;
    impl_source?: FileReadSource;
    /**
     * View Range
     */
    view_range?: Array<number> | null;
};

/**
 * FileReadSource
 */
export type FileReadSource = 'oh_aci' | 'default';

/**
 * FileWriteAction
 */
export type FileWriteAction = {
    /**
     * Path
     */
    path: string;
    /**
     * Content
     */
    content: string;
    /**
     * Start
     */
    start?: number;
    /**
     * End
     */
    end?: number;
    /**
     * Thought
     */
    thought?: string;
    /**
     * Action
     */
    action?: string;
    security_risk?: ActionSecurityRisk | null;
};

/**
 * GETCustomSecrets
 * Custom secrets names
 */
export type GetCustomSecrets = {
    /**
     * Custom Secrets
     */
    custom_secrets?: Array<CustomSecretWithoutValueModel> | null;
};

/**
 * GETSettingsModel
 * Settings with additional token data for the frontend
 */
export type GetSettingsModelReadable = {
    /**
     * Language
     */
    language?: string | null;
    /**
     * Agent
     */
    agent?: string | null;
    /**
     * Max Iterations
     */
    max_iterations?: number | null;
    /**
     * Security Analyzer
     */
    security_analyzer?: string | null;
    /**
     * Confirmation Mode
     */
    confirmation_mode?: boolean | null;
    /**
     * Llm Model
     */
    llm_model?: string | null;
    /**
     * Llm Api Key
     */
    llm_api_key?: string | null;
    /**
     * Llm Base Url
     */
    llm_base_url?: string | null;
    /**
     * Remote Runtime Resource Factor
     */
    remote_runtime_resource_factor?: number | null;
    secrets_store?: UserSecretsOutput;
    /**
     * Enable Default Condenser
     */
    enable_default_condenser?: boolean;
    /**
     * Enable Sound Notifications
     */
    enable_sound_notifications?: boolean;
    /**
     * Enable Proactive Conversation Starters
     */
    enable_proactive_conversation_starters?: boolean;
    /**
     * User Consents To Analytics
     */
    user_consents_to_analytics?: boolean | null;
    /**
     * Sandbox Base Container Image
     */
    sandbox_base_container_image?: string | null;
    /**
     * Sandbox Runtime Container Image
     */
    sandbox_runtime_container_image?: string | null;
    mcp_config?: McpConfig | null;
    /**
     * Search Api Key
     */
    search_api_key?: string | null;
    /**
     * Email
     */
    email?: string | null;
    /**
     * Email Verified
     */
    email_verified?: boolean | null;
    /**
     * Provider Tokens Set
     */
    provider_tokens_set?: {
        [key in ProviderType]?: string;
    } | null;
    /**
     * Llm Api Key Set
     */
    llm_api_key_set: boolean;
    /**
     * Search Api Key Set
     */
    search_api_key_set?: boolean;
};

/**
 * GETSettingsModel
 * Settings with additional token data for the frontend
 */
export type GetSettingsModelWritable = {
    /**
     * Language
     */
    language?: string | null;
    /**
     * Agent
     */
    agent?: string | null;
    /**
     * Max Iterations
     */
    max_iterations?: number | null;
    /**
     * Security Analyzer
     */
    security_analyzer?: string | null;
    /**
     * Confirmation Mode
     */
    confirmation_mode?: boolean | null;
    /**
     * Llm Model
     */
    llm_model?: string | null;
    /**
     * Llm Api Key
     */
    llm_api_key?: string | null;
    /**
     * Llm Base Url
     */
    llm_base_url?: string | null;
    /**
     * Remote Runtime Resource Factor
     */
    remote_runtime_resource_factor?: number | null;
    secrets_store?: UserSecretsOutput;
    /**
     * Enable Default Condenser
     */
    enable_default_condenser?: boolean;
    /**
     * Enable Sound Notifications
     */
    enable_sound_notifications?: boolean;
    /**
     * Enable Proactive Conversation Starters
     */
    enable_proactive_conversation_starters?: boolean;
    /**
     * User Consents To Analytics
     */
    user_consents_to_analytics?: boolean | null;
    /**
     * Sandbox Base Container Image
     */
    sandbox_base_container_image?: string | null;
    /**
     * Sandbox Runtime Container Image
     */
    sandbox_runtime_container_image?: string | null;
    mcp_config?: McpConfig | null;
    /**
     * Search Api Key
     */
    search_api_key?: string | null;
    /**
     * Email
     */
    email?: string | null;
    /**
     * Email Verified
     */
    email_verified?: boolean | null;
    /**
     * Provider Tokens Set
     */
    provider_tokens_set?: {
        [key in ProviderType]?: string;
    } | null;
    /**
     * Llm Api Key Set
     */
    llm_api_key_set: boolean;
    /**
     * Search Api Key Set
     */
    search_api_key_set?: boolean;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * IPythonRunCellAction
 */
export type IPythonRunCellAction = {
    /**
     * Code
     */
    code: string;
    /**
     * Thought
     */
    thought?: string;
    /**
     * Include Extra
     */
    include_extra?: boolean;
    /**
     * Action
     */
    action?: string;
    confirmation_state?: ActionConfirmationStatus;
    security_risk?: ActionSecurityRisk | null;
    /**
     * Kernel Init Code
     */
    kernel_init_code?: string;
};

/**
 * InitSessionRequest
 */
export type InitSessionRequest = {
    /**
     * Repository
     */
    repository?: string | null;
    git_provider?: ProviderType | null;
    /**
     * Selected Branch
     */
    selected_branch?: string | null;
    /**
     * Initial User Msg
     */
    initial_user_msg?: string | null;
    /**
     * Image Urls
     */
    image_urls?: Array<string> | null;
    /**
     * Replay Json
     */
    replay_json?: string | null;
    suggested_task?: SuggestedTask | null;
    /**
     * Conversation Instructions
     */
    conversation_instructions?: string | null;
};

/**
 * MCPAction
 */
export type McpAction = {
    /**
     * Name
     */
    name: string;
    /**
     * Arguments
     */
    arguments?: {
        [key: string]: unknown;
    };
    /**
     * Thought
     */
    thought?: string;
    /**
     * Action
     */
    action?: string;
    security_risk?: ActionSecurityRisk | null;
};

/**
 * MCPConfig
 * Configuration for MCP (Message Control Protocol) settings.
 *
 * Attributes:
 * sse_servers: List of MCP SSE server configs
 * stdio_servers: List of MCP stdio server configs. These servers will be added to the MCP Router running inside runtime container.
 */
export type McpConfig = {
    /**
     * Sse Servers
     */
    sse_servers?: Array<McpsseServerConfig>;
    /**
     * Stdio Servers
     */
    stdio_servers?: Array<McpStdioServerConfig>;
    /**
     * Shttp Servers
     */
    shttp_servers?: Array<McpshttpServerConfig>;
};

/**
 * MCPSHTTPServerConfig
 */
export type McpshttpServerConfig = {
    /**
     * Url
     */
    url: string;
    /**
     * Api Key
     */
    api_key?: string | null;
};

/**
 * MCPSSEServerConfig
 * Configuration for a single MCP server.
 *
 * Attributes:
 * url: The server URL
 * api_key: Optional API key for authentication
 */
export type McpsseServerConfig = {
    /**
     * Url
     */
    url: string;
    /**
     * Api Key
     */
    api_key?: string | null;
};

/**
 * MCPStdioServerConfig
 * Configuration for a MCP server that uses stdio.
 *
 * Attributes:
 * name: The name of the server
 * command: The command to run the server
 * args: The arguments to pass to the server
 * env: The environment variables to set for the server
 */
export type McpStdioServerConfig = {
    /**
     * Name
     */
    name: string;
    /**
     * Command
     */
    command: string;
    /**
     * Args
     */
    args?: Array<string>;
    /**
     * Env
     */
    env?: {
        [key: string]: string;
    };
};

/**
 * MessageAction
 */
export type MessageAction = {
    /**
     * Content
     */
    content: string;
    /**
     * Image Urls
     */
    image_urls?: Array<string> | null;
    /**
     * Wait For Response
     */
    wait_for_response?: boolean;
    /**
     * Action
     */
    action?: string;
    security_risk?: ActionSecurityRisk | null;
};

/**
 * NullAction
 */
export type NullAction = {
    /**
     * Action
     */
    action?: string;
};

/**
 * POSTProviderModel
 * Settings for POST requests
 */
export type PostProviderModel = {
    mcp_config?: McpConfig | null;
    /**
     * Provider Tokens
     */
    provider_tokens?: {
        [key in ProviderType]?: string;
    };
};

/**
 * ProviderToken
 */
export type ProviderTokenReadable = {
    /**
     * Token
     */
    token?: string | null;
    /**
     * User Id
     */
    user_id?: string | null;
    /**
     * Host
     */
    host?: string | null;
};

/**
 * ProviderToken
 */
export type ProviderTokenWritable = {
    /**
     * Token
     */
    token?: string | null;
    /**
     * User Id
     */
    user_id?: string | null;
    /**
     * Host
     */
    host?: string | null;
};

/**
 * ProviderType
 */
export type ProviderType = 'github' | 'gitlab' | 'bitbucket';

/**
 * RecallAction
 */
export type RecallAction = {
    recall_type: RecallType;
    /**
     * Query
     */
    query?: string;
    /**
     * Thought
     */
    thought?: string;
    /**
     * Action
     */
    action?: string;
};

/**
 * RecallType
 * The type of information that can be retrieved from microagents.
 */
export type RecallType = 'workspace_context' | 'knowledge';

/**
 * Repository
 */
export type Repository = {
    /**
     * Id
     */
    id: string;
    /**
     * Full Name
     */
    full_name: string;
    git_provider: ProviderType;
    /**
     * Is Public
     */
    is_public: boolean;
    /**
     * Stargazers Count
     */
    stargazers_count?: number | null;
    /**
     * Link Header
     */
    link_header?: string | null;
    /**
     * Pushed At
     */
    pushed_at?: string | null;
};

/**
 * RuntimeInfoResponse
 */
export type RuntimeInfoResponse = {
    /**
     * Session Id
     */
    session_id: string;
    /**
     * Runtime Type
     */
    runtime_type: string;
    /**
     * Is Alive
     */
    is_alive: boolean;
    /**
     * Last Active
     */
    last_active: number;
};

/**
 * RuntimeSessionResponse
 */
export type RuntimeSessionResponse = {
    /**
     * Status
     */
    status: string;
    /**
     * Session Id
     */
    session_id: string;
    /**
     * Message
     */
    message?: string | null;
};

/**
 * RuntimeStatus
 */
export type RuntimeStatus = 'STATUS$STOPPED' | 'STATUS$BUILDING_RUNTIME' | 'STATUS$STARTING_RUNTIME' | 'STATUS$RUNTIME_STARTED' | 'STATUS$SETTING_UP_WORKSPACE' | 'STATUS$SETTING_UP_GIT_HOOKS' | 'STATUS$READY';

/**
 * Settings
 * Persisted settings for OpenHands sessions
 */
export type SettingsReadable = {
    /**
     * Language
     */
    language?: string | null;
    /**
     * Agent
     */
    agent?: string | null;
    /**
     * Max Iterations
     */
    max_iterations?: number | null;
    /**
     * Security Analyzer
     */
    security_analyzer?: string | null;
    /**
     * Confirmation Mode
     */
    confirmation_mode?: boolean | null;
    /**
     * Llm Model
     */
    llm_model?: string | null;
    /**
     * Llm Api Key
     */
    llm_api_key?: string | null;
    /**
     * Llm Base Url
     */
    llm_base_url?: string | null;
    /**
     * Remote Runtime Resource Factor
     */
    remote_runtime_resource_factor?: number | null;
    secrets_store?: UserSecretsInput;
    /**
     * Enable Default Condenser
     */
    enable_default_condenser?: boolean;
    /**
     * Enable Sound Notifications
     */
    enable_sound_notifications?: boolean;
    /**
     * Enable Proactive Conversation Starters
     */
    enable_proactive_conversation_starters?: boolean;
    /**
     * User Consents To Analytics
     */
    user_consents_to_analytics?: boolean | null;
    /**
     * Sandbox Base Container Image
     */
    sandbox_base_container_image?: string | null;
    /**
     * Sandbox Runtime Container Image
     */
    sandbox_runtime_container_image?: string | null;
    mcp_config?: McpConfig | null;
    /**
     * Search Api Key
     */
    search_api_key?: string | null;
    /**
     * Email
     */
    email?: string | null;
    /**
     * Email Verified
     */
    email_verified?: boolean | null;
};

/**
 * Settings
 * Persisted settings for OpenHands sessions
 */
export type SettingsWritable = {
    /**
     * Language
     */
    language?: string | null;
    /**
     * Agent
     */
    agent?: string | null;
    /**
     * Max Iterations
     */
    max_iterations?: number | null;
    /**
     * Security Analyzer
     */
    security_analyzer?: string | null;
    /**
     * Confirmation Mode
     */
    confirmation_mode?: boolean | null;
    /**
     * Llm Model
     */
    llm_model?: string | null;
    /**
     * Llm Api Key
     */
    llm_api_key?: string | null;
    /**
     * Llm Base Url
     */
    llm_base_url?: string | null;
    /**
     * Remote Runtime Resource Factor
     */
    remote_runtime_resource_factor?: number | null;
    secrets_store?: UserSecretsInput;
    /**
     * Enable Default Condenser
     */
    enable_default_condenser?: boolean;
    /**
     * Enable Sound Notifications
     */
    enable_sound_notifications?: boolean;
    /**
     * Enable Proactive Conversation Starters
     */
    enable_proactive_conversation_starters?: boolean;
    /**
     * User Consents To Analytics
     */
    user_consents_to_analytics?: boolean | null;
    /**
     * Sandbox Base Container Image
     */
    sandbox_base_container_image?: string | null;
    /**
     * Sandbox Runtime Container Image
     */
    sandbox_runtime_container_image?: string | null;
    mcp_config?: McpConfig | null;
    /**
     * Search Api Key
     */
    search_api_key?: string | null;
    /**
     * Email
     */
    email?: string | null;
    /**
     * Email Verified
     */
    email_verified?: boolean | null;
};

/**
 * SuggestedTask
 */
export type SuggestedTask = {
    git_provider: ProviderType;
    task_type: TaskType;
    /**
     * Repo
     */
    repo: string;
    /**
     * Issue Number
     */
    issue_number: number;
    /**
     * Title
     */
    title: string;
};

/**
 * SystemMessageAction
 */
export type SystemMessageAction = {
    /**
     * Content
     */
    content: string;
    /**
     * Tools
     */
    tools?: Array<unknown> | null;
    /**
     * Openhands Version
     */
    openhands_version?: string | null;
    /**
     * Agent Class
     */
    agent_class?: string | null;
    action?: ActionType;
};

/**
 * TaskType
 */
export type TaskType = 'MERGE_CONFLICTS' | 'FAILING_CHECKS' | 'UNRESOLVED_COMMENTS' | 'OPEN_ISSUE' | 'OPEN_PR';

/**
 * User
 */
export type User = {
    /**
     * Id
     */
    id: string;
    /**
     * Login
     */
    login: string;
    /**
     * Avatar Url
     */
    avatar_url: string;
    /**
     * Company
     */
    company?: string | null;
    /**
     * Name
     */
    name?: string | null;
    /**
     * Email
     */
    email?: string | null;
};

/**
 * UserSecrets
 */
export type UserSecretsInput = {
    /**
     * Provider Tokens
     */
    provider_tokens?: {
        [key: string]: string;
    };
    /**
     * Custom Secrets
     */
    custom_secrets?: {
        [key: string]: string;
    };
};

/**
 * UserSecrets
 */
export type UserSecretsOutput = {
    /**
     * Provider Tokens
     */
    provider_tokens?: {
        [key: string]: {
            [key: string]: string | unknown;
        };
    };
    /**
     * Custom Secrets
     */
    custom_secrets?: {
        [key: string]: string;
    };
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

export type GetLitellmModelsApiOptionsModelsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/options/models';
};

export type GetLitellmModelsApiOptionsModelsGetResponses = {
    /**
     * Response Get Litellm Models Api Options Models Get
     * Successful Response
     */
    200: Array<string>;
};

export type GetLitellmModelsApiOptionsModelsGetResponse = GetLitellmModelsApiOptionsModelsGetResponses[keyof GetLitellmModelsApiOptionsModelsGetResponses];

export type GetAgentsApiOptionsAgentsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/options/agents';
};

export type GetAgentsApiOptionsAgentsGetResponses = {
    /**
     * Response Get Agents Api Options Agents Get
     * Successful Response
     */
    200: Array<string>;
};

export type GetAgentsApiOptionsAgentsGetResponse = GetAgentsApiOptionsAgentsGetResponses[keyof GetAgentsApiOptionsAgentsGetResponses];

export type GetSecurityAnalyzersApiOptionsSecurityAnalyzersGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/options/security-analyzers';
};

export type GetSecurityAnalyzersApiOptionsSecurityAnalyzersGetResponses = {
    /**
     * Response Get Security Analyzers Api Options Security Analyzers Get
     * Successful Response
     */
    200: Array<string>;
};

export type GetSecurityAnalyzersApiOptionsSecurityAnalyzersGetResponse = GetSecurityAnalyzersApiOptionsSecurityAnalyzersGetResponses[keyof GetSecurityAnalyzersApiOptionsSecurityAnalyzersGetResponses];

export type GetConfigApiOptionsConfigGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/options/config';
};

export type GetConfigApiOptionsConfigGetResponses = {
    /**
     * Response Get Config Api Options Config Get
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type GetConfigApiOptionsConfigGetResponse = GetConfigApiOptionsConfigGetResponses[keyof GetConfigApiOptionsConfigGetResponses];

export type ListFilesApiConversationsConversationIdListFilesGetData = {
    body?: never;
    path: {
        /**
         * Conversation Id
         */
        conversation_id: string;
    };
    query?: {
        /**
         * Path
         */
        path?: string | null;
    };
    url: '/api/conversations/{conversation_id}/list-files';
};

export type ListFilesApiConversationsConversationIdListFilesGetErrors = {
    /**
     * Response 404 List Files Api Conversations  Conversation Id  List Files Get
     * Runtime not initialized
     */
    404: {
        [key: string]: unknown;
    };
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Response 500 List Files Api Conversations  Conversation Id  List Files Get
     * Error listing or filtering files
     */
    500: {
        [key: string]: unknown;
    };
};

export type ListFilesApiConversationsConversationIdListFilesGetError = ListFilesApiConversationsConversationIdListFilesGetErrors[keyof ListFilesApiConversationsConversationIdListFilesGetErrors];

export type ListFilesApiConversationsConversationIdListFilesGetResponses = {
    /**
     * Response List Files Api Conversations  Conversation Id  List Files Get
     * Successful Response
     */
    200: Array<string>;
};

export type ListFilesApiConversationsConversationIdListFilesGetResponse = ListFilesApiConversationsConversationIdListFilesGetResponses[keyof ListFilesApiConversationsConversationIdListFilesGetResponses];

export type SelectFileApiConversationsConversationIdSelectFileGetData = {
    body?: never;
    path: {
        /**
         * Conversation Id
         */
        conversation_id: string;
    };
    query: {
        /**
         * File
         */
        file: string;
    };
    url: '/api/conversations/{conversation_id}/select-file';
};

export type SelectFileApiConversationsConversationIdSelectFileGetErrors = {
    /**
     * Response 415 Select File Api Conversations  Conversation Id  Select File Get
     * Unsupported media type
     */
    415: {
        [key: string]: unknown;
    };
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Response 500 Select File Api Conversations  Conversation Id  Select File Get
     * Error opening file
     */
    500: {
        [key: string]: unknown;
    };
};

export type SelectFileApiConversationsConversationIdSelectFileGetError = SelectFileApiConversationsConversationIdSelectFileGetErrors[keyof SelectFileApiConversationsConversationIdSelectFileGetErrors];

export type SelectFileApiConversationsConversationIdSelectFileGetResponses = {
    /**
     * Response 200 Select File Api Conversations  Conversation Id  Select File Get
     * File content returned as JSON
     */
    200: {
        [key: string]: string;
    };
};

export type SelectFileApiConversationsConversationIdSelectFileGetResponse = SelectFileApiConversationsConversationIdSelectFileGetResponses[keyof SelectFileApiConversationsConversationIdSelectFileGetResponses];

export type ZipCurrentWorkspaceApiConversationsConversationIdZipDirectoryGetData = {
    body?: never;
    path: {
        /**
         * Conversation Id
         */
        conversation_id: string;
    };
    query?: never;
    url: '/api/conversations/{conversation_id}/zip-directory';
};

export type ZipCurrentWorkspaceApiConversationsConversationIdZipDirectoryGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Response 500 Zip Current Workspace Api Conversations  Conversation Id  Zip Directory Get
     * Error zipping workspace
     */
    500: {
        [key: string]: unknown;
    };
};

export type ZipCurrentWorkspaceApiConversationsConversationIdZipDirectoryGetError = ZipCurrentWorkspaceApiConversationsConversationIdZipDirectoryGetErrors[keyof ZipCurrentWorkspaceApiConversationsConversationIdZipDirectoryGetErrors];

export type ZipCurrentWorkspaceApiConversationsConversationIdZipDirectoryGetResponses = {
    /**
     * Zipped workspace returned as FileResponse
     */
    200: unknown;
};

export type GitChangesApiConversationsConversationIdGitChangesGetData = {
    body?: never;
    path: {
        /**
         * Conversation Id
         */
        conversation_id: string;
    };
    query?: never;
    url: '/api/conversations/{conversation_id}/git/changes';
};

export type GitChangesApiConversationsConversationIdGitChangesGetErrors = {
    /**
     * Response 404 Git Changes Api Conversations  Conversation Id  Git Changes Get
     * Not a git repository
     */
    404: {
        [key: string]: unknown;
    };
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Response 500 Git Changes Api Conversations  Conversation Id  Git Changes Get
     * Error getting changes
     */
    500: {
        [key: string]: unknown;
    };
};

export type GitChangesApiConversationsConversationIdGitChangesGetError = GitChangesApiConversationsConversationIdGitChangesGetErrors[keyof GitChangesApiConversationsConversationIdGitChangesGetErrors];

export type GitChangesApiConversationsConversationIdGitChangesGetResponses = {
    /**
     * Response Git Changes Api Conversations  Conversation Id  Git Changes Get
     * Successful Response
     */
    200: Array<{
        [key: string]: string;
    }>;
};

export type GitChangesApiConversationsConversationIdGitChangesGetResponse = GitChangesApiConversationsConversationIdGitChangesGetResponses[keyof GitChangesApiConversationsConversationIdGitChangesGetResponses];

export type GitDiffApiConversationsConversationIdGitDiffGetData = {
    body?: never;
    path: {
        /**
         * Conversation Id
         */
        conversation_id: string;
    };
    query: {
        /**
         * Path
         */
        path: string;
    };
    url: '/api/conversations/{conversation_id}/git/diff';
};

export type GitDiffApiConversationsConversationIdGitDiffGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Response 500 Git Diff Api Conversations  Conversation Id  Git Diff Get
     * Error getting diff
     */
    500: {
        [key: string]: unknown;
    };
};

export type GitDiffApiConversationsConversationIdGitDiffGetError = GitDiffApiConversationsConversationIdGitDiffGetErrors[keyof GitDiffApiConversationsConversationIdGitDiffGetErrors];

export type GitDiffApiConversationsConversationIdGitDiffGetResponses = {
    /**
     * Response Git Diff Api Conversations  Conversation Id  Git Diff Get
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type GitDiffApiConversationsConversationIdGitDiffGetResponse = GitDiffApiConversationsConversationIdGitDiffGetResponses[keyof GitDiffApiConversationsConversationIdGitDiffGetResponses];

export type SubmitFeedbackApiConversationsConversationIdSubmitFeedbackPostData = {
    body?: never;
    path: {
        /**
         * Conversation Id
         */
        conversation_id: string;
    };
    query?: never;
    url: '/api/conversations/{conversation_id}/submit-feedback';
};

export type SubmitFeedbackApiConversationsConversationIdSubmitFeedbackPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SubmitFeedbackApiConversationsConversationIdSubmitFeedbackPostError = SubmitFeedbackApiConversationsConversationIdSubmitFeedbackPostErrors[keyof SubmitFeedbackApiConversationsConversationIdSubmitFeedbackPostErrors];

export type SubmitFeedbackApiConversationsConversationIdSubmitFeedbackPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetRemoteRuntimeConfigApiConversationsConversationIdConfigGetData = {
    body?: never;
    path: {
        /**
         * Conversation Id
         */
        conversation_id: string;
    };
    query?: never;
    url: '/api/conversations/{conversation_id}/config';
};

export type GetRemoteRuntimeConfigApiConversationsConversationIdConfigGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetRemoteRuntimeConfigApiConversationsConversationIdConfigGetError = GetRemoteRuntimeConfigApiConversationsConversationIdConfigGetErrors[keyof GetRemoteRuntimeConfigApiConversationsConversationIdConfigGetErrors];

export type GetRemoteRuntimeConfigApiConversationsConversationIdConfigGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetVscodeUrlApiConversationsConversationIdVscodeUrlGetData = {
    body?: never;
    path: {
        /**
         * Conversation Id
         */
        conversation_id: string;
    };
    query?: never;
    url: '/api/conversations/{conversation_id}/vscode-url';
};

export type GetVscodeUrlApiConversationsConversationIdVscodeUrlGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetVscodeUrlApiConversationsConversationIdVscodeUrlGetError = GetVscodeUrlApiConversationsConversationIdVscodeUrlGetErrors[keyof GetVscodeUrlApiConversationsConversationIdVscodeUrlGetErrors];

export type GetVscodeUrlApiConversationsConversationIdVscodeUrlGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetHostsApiConversationsConversationIdWebHostsGetData = {
    body?: never;
    path: {
        /**
         * Conversation Id
         */
        conversation_id: string;
    };
    query?: never;
    url: '/api/conversations/{conversation_id}/web-hosts';
};

export type GetHostsApiConversationsConversationIdWebHostsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetHostsApiConversationsConversationIdWebHostsGetError = GetHostsApiConversationsConversationIdWebHostsGetErrors[keyof GetHostsApiConversationsConversationIdWebHostsGetErrors];

export type GetHostsApiConversationsConversationIdWebHostsGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type SearchEventsApiConversationsConversationIdEventsGetData = {
    /**
     * Filter
     */
    body?: EventFilter | null;
    path: {
        /**
         * Conversation Id
         */
        conversation_id: string;
    };
    query?: {
        /**
         * Start Id
         */
        start_id?: number;
        /**
         * End Id
         */
        end_id?: number | null;
        /**
         * Reverse
         */
        reverse?: boolean;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/conversations/{conversation_id}/events';
};

export type SearchEventsApiConversationsConversationIdEventsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SearchEventsApiConversationsConversationIdEventsGetError = SearchEventsApiConversationsConversationIdEventsGetErrors[keyof SearchEventsApiConversationsConversationIdEventsGetErrors];

export type SearchEventsApiConversationsConversationIdEventsGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type AddEventApiConversationsConversationIdEventsPostData = {
    body?: never;
    path: {
        /**
         * Conversation Id
         */
        conversation_id: string;
    };
    query?: never;
    url: '/api/conversations/{conversation_id}/events';
};

export type AddEventApiConversationsConversationIdEventsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AddEventApiConversationsConversationIdEventsPostError = AddEventApiConversationsConversationIdEventsPostErrors[keyof AddEventApiConversationsConversationIdEventsPostErrors];

export type AddEventApiConversationsConversationIdEventsPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetMicroagentsApiConversationsConversationIdMicroagentsGetData = {
    body?: never;
    path: {
        /**
         * Conversation Id
         */
        conversation_id: string;
    };
    query?: never;
    url: '/api/conversations/{conversation_id}/microagents';
};

export type GetMicroagentsApiConversationsConversationIdMicroagentsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetMicroagentsApiConversationsConversationIdMicroagentsGetError = GetMicroagentsApiConversationsConversationIdMicroagentsGetErrors[keyof GetMicroagentsApiConversationsConversationIdMicroagentsGetErrors];

export type GetMicroagentsApiConversationsConversationIdMicroagentsGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type SearchConversationsApiConversationsGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Page Id
         */
        page_id?: string | null;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/conversations';
};

export type SearchConversationsApiConversationsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SearchConversationsApiConversationsGetError = SearchConversationsApiConversationsGetErrors[keyof SearchConversationsApiConversationsGetErrors];

export type SearchConversationsApiConversationsGetResponses = {
    /**
     * Successful Response
     */
    200: ConversationInfoResultSet;
};

export type SearchConversationsApiConversationsGetResponse = SearchConversationsApiConversationsGetResponses[keyof SearchConversationsApiConversationsGetResponses];

export type NewConversationApiConversationsPostData = {
    body: InitSessionRequest;
    path?: never;
    query?: never;
    url: '/api/conversations';
};

export type NewConversationApiConversationsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type NewConversationApiConversationsPostError = NewConversationApiConversationsPostErrors[keyof NewConversationApiConversationsPostErrors];

export type NewConversationApiConversationsPostResponses = {
    /**
     * Successful Response
     */
    200: ConversationResponse;
};

export type NewConversationApiConversationsPostResponse = NewConversationApiConversationsPostResponses[keyof NewConversationApiConversationsPostResponses];

export type DeleteConversationApiConversationsConversationIdDeleteData = {
    body?: never;
    path: {
        /**
         * Conversation Id
         */
        conversation_id: string;
    };
    query?: never;
    url: '/api/conversations/{conversation_id}';
};

export type DeleteConversationApiConversationsConversationIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteConversationApiConversationsConversationIdDeleteError = DeleteConversationApiConversationsConversationIdDeleteErrors[keyof DeleteConversationApiConversationsConversationIdDeleteErrors];

export type DeleteConversationApiConversationsConversationIdDeleteResponses = {
    /**
     * Response Delete Conversation Api Conversations  Conversation Id  Delete
     * Successful Response
     */
    200: boolean;
};

export type DeleteConversationApiConversationsConversationIdDeleteResponse = DeleteConversationApiConversationsConversationIdDeleteResponses[keyof DeleteConversationApiConversationsConversationIdDeleteResponses];

export type GetConversationApiConversationsConversationIdGetData = {
    body?: never;
    path: {
        /**
         * Conversation Id
         */
        conversation_id: string;
    };
    query?: never;
    url: '/api/conversations/{conversation_id}';
};

export type GetConversationApiConversationsConversationIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetConversationApiConversationsConversationIdGetError = GetConversationApiConversationsConversationIdGetErrors[keyof GetConversationApiConversationsConversationIdGetErrors];

export type GetConversationApiConversationsConversationIdGetResponses = {
    /**
     * Response Get Conversation Api Conversations  Conversation Id  Get
     * Successful Response
     */
    200: ConversationInfo | null;
};

export type GetConversationApiConversationsConversationIdGetResponse = GetConversationApiConversationsConversationIdGetResponses[keyof GetConversationApiConversationsConversationIdGetResponses];

export type GetPromptApiConversationsConversationIdRememberPromptGetData = {
    body?: never;
    path: {
        /**
         * Conversation Id
         */
        conversation_id: string;
    };
    query: {
        /**
         * Event Id
         */
        event_id: number;
    };
    url: '/api/conversations/{conversation_id}/remember_prompt';
};

export type GetPromptApiConversationsConversationIdRememberPromptGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetPromptApiConversationsConversationIdRememberPromptGetError = GetPromptApiConversationsConversationIdRememberPromptGetErrors[keyof GetPromptApiConversationsConversationIdRememberPromptGetErrors];

export type GetPromptApiConversationsConversationIdRememberPromptGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type StartConversationApiConversationsConversationIdStartPostData = {
    body?: never;
    path: {
        /**
         * Conversation Id
         */
        conversation_id: string;
    };
    query?: never;
    url: '/api/conversations/{conversation_id}/start';
};

export type StartConversationApiConversationsConversationIdStartPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type StartConversationApiConversationsConversationIdStartPostError = StartConversationApiConversationsConversationIdStartPostErrors[keyof StartConversationApiConversationsConversationIdStartPostErrors];

export type StartConversationApiConversationsConversationIdStartPostResponses = {
    /**
     * Successful Response
     */
    200: ConversationResponse;
};

export type StartConversationApiConversationsConversationIdStartPostResponse = StartConversationApiConversationsConversationIdStartPostResponses[keyof StartConversationApiConversationsConversationIdStartPostResponses];

export type StopConversationApiConversationsConversationIdStopPostData = {
    body?: never;
    path: {
        /**
         * Conversation Id
         */
        conversation_id: string;
    };
    query?: never;
    url: '/api/conversations/{conversation_id}/stop';
};

export type StopConversationApiConversationsConversationIdStopPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type StopConversationApiConversationsConversationIdStopPostError = StopConversationApiConversationsConversationIdStopPostErrors[keyof StopConversationApiConversationsConversationIdStopPostErrors];

export type StopConversationApiConversationsConversationIdStopPostResponses = {
    /**
     * Successful Response
     */
    200: ConversationResponse;
};

export type StopConversationApiConversationsConversationIdStopPostResponse = StopConversationApiConversationsConversationIdStopPostResponses[keyof StopConversationApiConversationsConversationIdStopPostResponses];

export type ListSupportedActionsApiRuntimeActionsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/runtime/actions';
};

export type ListSupportedActionsApiRuntimeActionsGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ListRuntimeSessionsApiRuntimeSessionsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/runtime/sessions';
};

export type ListRuntimeSessionsApiRuntimeSessionsGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type CreateRuntimeSessionApiRuntimeSessionsPostData = {
    body: CreateRuntimeSessionRequest;
    path?: never;
    query?: never;
    url: '/api/runtime/sessions';
};

export type CreateRuntimeSessionApiRuntimeSessionsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateRuntimeSessionApiRuntimeSessionsPostError = CreateRuntimeSessionApiRuntimeSessionsPostErrors[keyof CreateRuntimeSessionApiRuntimeSessionsPostErrors];

export type CreateRuntimeSessionApiRuntimeSessionsPostResponses = {
    /**
     * Successful Response
     */
    200: RuntimeSessionResponse;
};

export type CreateRuntimeSessionApiRuntimeSessionsPostResponse = CreateRuntimeSessionApiRuntimeSessionsPostResponses[keyof CreateRuntimeSessionApiRuntimeSessionsPostResponses];

export type CloseRuntimeSessionApiRuntimeSessionsSessionIdDeleteData = {
    body?: never;
    path: {
        /**
         * Session Id
         */
        session_id: string;
    };
    query?: never;
    url: '/api/runtime/sessions/{session_id}';
};

export type CloseRuntimeSessionApiRuntimeSessionsSessionIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CloseRuntimeSessionApiRuntimeSessionsSessionIdDeleteError = CloseRuntimeSessionApiRuntimeSessionsSessionIdDeleteErrors[keyof CloseRuntimeSessionApiRuntimeSessionsSessionIdDeleteErrors];

export type CloseRuntimeSessionApiRuntimeSessionsSessionIdDeleteResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetRuntimeSessionInfoApiRuntimeSessionsSessionIdGetData = {
    body?: never;
    path: {
        /**
         * Session Id
         */
        session_id: string;
    };
    query?: never;
    url: '/api/runtime/sessions/{session_id}';
};

export type GetRuntimeSessionInfoApiRuntimeSessionsSessionIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetRuntimeSessionInfoApiRuntimeSessionsSessionIdGetError = GetRuntimeSessionInfoApiRuntimeSessionsSessionIdGetErrors[keyof GetRuntimeSessionInfoApiRuntimeSessionsSessionIdGetErrors];

export type GetRuntimeSessionInfoApiRuntimeSessionsSessionIdGetResponses = {
    /**
     * Successful Response
     */
    200: RuntimeInfoResponse;
};

export type GetRuntimeSessionInfoApiRuntimeSessionsSessionIdGetResponse = GetRuntimeSessionInfoApiRuntimeSessionsSessionIdGetResponses[keyof GetRuntimeSessionInfoApiRuntimeSessionsSessionIdGetResponses];

export type ExecuteCommandApiRuntimeSessionsSessionIdExecutePostData = {
    body: ActionRequest;
    path: {
        /**
         * Session Id
         */
        session_id: string;
    };
    query?: never;
    url: '/api/runtime/sessions/{session_id}/execute';
};

export type ExecuteCommandApiRuntimeSessionsSessionIdExecutePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ExecuteCommandApiRuntimeSessionsSessionIdExecutePostError = ExecuteCommandApiRuntimeSessionsSessionIdExecutePostErrors[keyof ExecuteCommandApiRuntimeSessionsSessionIdExecutePostErrors];

export type ExecuteCommandApiRuntimeSessionsSessionIdExecutePostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetRuntimeSessionConfigApiRuntimeSessionsSessionIdConfigGetData = {
    body?: never;
    path: {
        /**
         * Session Id
         */
        session_id: string;
    };
    query?: never;
    url: '/api/runtime/sessions/{session_id}/config';
};

export type GetRuntimeSessionConfigApiRuntimeSessionsSessionIdConfigGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetRuntimeSessionConfigApiRuntimeSessionsSessionIdConfigGetError = GetRuntimeSessionConfigApiRuntimeSessionsSessionIdConfigGetErrors[keyof GetRuntimeSessionConfigApiRuntimeSessionsSessionIdConfigGetErrors];

export type GetRuntimeSessionConfigApiRuntimeSessionsSessionIdConfigGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetVscodeUrlApiRuntimeSessionsSessionIdVscodeUrlGetData = {
    body?: never;
    path: {
        /**
         * Session Id
         */
        session_id: string;
    };
    query?: never;
    url: '/api/runtime/sessions/{session_id}/vscode-url';
};

export type GetVscodeUrlApiRuntimeSessionsSessionIdVscodeUrlGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetVscodeUrlApiRuntimeSessionsSessionIdVscodeUrlGetError = GetVscodeUrlApiRuntimeSessionsSessionIdVscodeUrlGetErrors[keyof GetVscodeUrlApiRuntimeSessionsSessionIdVscodeUrlGetErrors];

export type GetVscodeUrlApiRuntimeSessionsSessionIdVscodeUrlGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetWebHostsApiRuntimeSessionsSessionIdWebHostsGetData = {
    body?: never;
    path: {
        /**
         * Session Id
         */
        session_id: string;
    };
    query?: never;
    url: '/api/runtime/sessions/{session_id}/web-hosts';
};

export type GetWebHostsApiRuntimeSessionsSessionIdWebHostsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetWebHostsApiRuntimeSessionsSessionIdWebHostsGetError = GetWebHostsApiRuntimeSessionsSessionIdWebHostsGetErrors[keyof GetWebHostsApiRuntimeSessionsSessionIdWebHostsGetErrors];

export type GetWebHostsApiRuntimeSessionsSessionIdWebHostsGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetRuntimeSessionEventsApiRuntimeSessionsSessionIdEventsGetData = {
    /**
     * Filter
     */
    body?: EventFilter | null;
    path: {
        /**
         * Session Id
         */
        session_id: string;
    };
    query?: {
        /**
         * Start Id
         */
        start_id?: number;
        /**
         * End Id
         */
        end_id?: number | null;
        /**
         * Reverse
         */
        reverse?: boolean;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/runtime/sessions/{session_id}/events';
};

export type GetRuntimeSessionEventsApiRuntimeSessionsSessionIdEventsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetRuntimeSessionEventsApiRuntimeSessionsSessionIdEventsGetError = GetRuntimeSessionEventsApiRuntimeSessionsSessionIdEventsGetErrors[keyof GetRuntimeSessionEventsApiRuntimeSessionsSessionIdEventsGetErrors];

export type GetRuntimeSessionEventsApiRuntimeSessionsSessionIdEventsGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type AddRuntimeSessionEventApiRuntimeSessionsSessionIdEventsPostData = {
    body: EventRequest;
    path: {
        /**
         * Session Id
         */
        session_id: string;
    };
    query?: never;
    url: '/api/runtime/sessions/{session_id}/events';
};

export type AddRuntimeSessionEventApiRuntimeSessionsSessionIdEventsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AddRuntimeSessionEventApiRuntimeSessionsSessionIdEventsPostError = AddRuntimeSessionEventApiRuntimeSessionsSessionIdEventsPostErrors[keyof AddRuntimeSessionEventApiRuntimeSessionsSessionIdEventsPostErrors];

export type AddRuntimeSessionEventApiRuntimeSessionsSessionIdEventsPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetRuntimeSessionScreenshotApiRuntimeBrowserSessionIdScreenshotGetData = {
    body?: never;
    path: {
        /**
         * Session Id
         */
        session_id: string;
    };
    query?: never;
    url: '/api/runtime/browser/{session_id}/screenshot';
};

export type GetRuntimeSessionScreenshotApiRuntimeBrowserSessionIdScreenshotGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetRuntimeSessionScreenshotApiRuntimeBrowserSessionIdScreenshotGetError = GetRuntimeSessionScreenshotApiRuntimeBrowserSessionIdScreenshotGetErrors[keyof GetRuntimeSessionScreenshotApiRuntimeBrowserSessionIdScreenshotGetErrors];

export type GetRuntimeSessionScreenshotApiRuntimeBrowserSessionIdScreenshotGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetBrowserStatusApiRuntimeBrowserSessionIdBrowserStatusGetData = {
    body?: never;
    path: {
        /**
         * Session Id
         */
        session_id: string;
    };
    query?: never;
    url: '/api/runtime/browser/{session_id}/browser-status';
};

export type GetBrowserStatusApiRuntimeBrowserSessionIdBrowserStatusGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetBrowserStatusApiRuntimeBrowserSessionIdBrowserStatusGetError = GetBrowserStatusApiRuntimeBrowserSessionIdBrowserStatusGetErrors[keyof GetBrowserStatusApiRuntimeBrowserSessionIdBrowserStatusGetErrors];

export type GetBrowserStatusApiRuntimeBrowserSessionIdBrowserStatusGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type LoadSettingsApiSettingsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/settings';
};

export type LoadSettingsApiSettingsGetErrors = {
    /**
     * Response 401 Load Settings Api Settings Get
     * Invalid token
     */
    401: {
        [key: string]: unknown;
    };
    /**
     * Response 404 Load Settings Api Settings Get
     * Settings not found
     */
    404: {
        [key: string]: unknown;
    };
};

export type LoadSettingsApiSettingsGetError = LoadSettingsApiSettingsGetErrors[keyof LoadSettingsApiSettingsGetErrors];

export type LoadSettingsApiSettingsGetResponses = {
    /**
     * Successful Response
     */
    200: GetSettingsModelReadable;
};

export type LoadSettingsApiSettingsGetResponse = LoadSettingsApiSettingsGetResponses[keyof LoadSettingsApiSettingsGetResponses];

export type StoreSettingsApiSettingsPostData = {
    body: SettingsWritable;
    path?: never;
    query?: never;
    url: '/api/settings';
};

export type StoreSettingsApiSettingsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Response 500 Store Settings Api Settings Post
     * Error storing settings
     */
    500: {
        [key: string]: unknown;
    };
};

export type StoreSettingsApiSettingsPostError = StoreSettingsApiSettingsPostErrors[keyof StoreSettingsApiSettingsPostErrors];

export type StoreSettingsApiSettingsPostResponses = {
    /**
     * Response 200 Store Settings Api Settings Post
     * Settings stored successfully
     */
    200: {
        [key: string]: unknown;
    };
};

export type StoreSettingsApiSettingsPostResponse = StoreSettingsApiSettingsPostResponses[keyof StoreSettingsApiSettingsPostResponses];

export type ResetSettingsApiResetSettingsPostData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/reset-settings';
};

export type ResetSettingsApiResetSettingsPostErrors = {
    /**
     * Response 410 Reset Settings Api Reset Settings Post
     * Reset settings functionality has been removed
     */
    410: {
        [key: string]: unknown;
    };
};

export type ResetSettingsApiResetSettingsPostError = ResetSettingsApiResetSettingsPostErrors[keyof ResetSettingsApiResetSettingsPostErrors];

export type ResetSettingsApiResetSettingsPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type StoreProviderTokensApiAddGitProvidersPostData = {
    body: PostProviderModel;
    path?: never;
    query?: never;
    url: '/api/add-git-providers';
};

export type StoreProviderTokensApiAddGitProvidersPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type StoreProviderTokensApiAddGitProvidersPostError = StoreProviderTokensApiAddGitProvidersPostErrors[keyof StoreProviderTokensApiAddGitProvidersPostErrors];

export type StoreProviderTokensApiAddGitProvidersPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type UnsetProviderTokensApiUnsetProviderTokensPostData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/unset-provider-tokens';
};

export type UnsetProviderTokensApiUnsetProviderTokensPostResponses = {
    /**
     * Response Unset Provider Tokens Api Unset Provider Tokens Post
     * Successful Response
     */
    200: {
        [key: string]: string;
    };
};

export type UnsetProviderTokensApiUnsetProviderTokensPostResponse = UnsetProviderTokensApiUnsetProviderTokensPostResponses[keyof UnsetProviderTokensApiUnsetProviderTokensPostResponses];

export type LoadCustomSecretsNamesApiSecretsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/secrets';
};

export type LoadCustomSecretsNamesApiSecretsGetResponses = {
    /**
     * Successful Response
     */
    200: GetCustomSecrets;
};

export type LoadCustomSecretsNamesApiSecretsGetResponse = LoadCustomSecretsNamesApiSecretsGetResponses[keyof LoadCustomSecretsNamesApiSecretsGetResponses];

export type CreateCustomSecretApiSecretsPostData = {
    body: CustomSecretModelWritable;
    path?: never;
    query?: never;
    url: '/api/secrets';
};

export type CreateCustomSecretApiSecretsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateCustomSecretApiSecretsPostError = CreateCustomSecretApiSecretsPostErrors[keyof CreateCustomSecretApiSecretsPostErrors];

export type CreateCustomSecretApiSecretsPostResponses = {
    /**
     * Response Create Custom Secret Api Secrets Post
     * Successful Response
     */
    200: {
        [key: string]: string;
    };
};

export type CreateCustomSecretApiSecretsPostResponse = CreateCustomSecretApiSecretsPostResponses[keyof CreateCustomSecretApiSecretsPostResponses];

export type DeleteCustomSecretApiSecretsSecretIdDeleteData = {
    body?: never;
    path: {
        /**
         * Secret Id
         */
        secret_id: string;
    };
    query?: never;
    url: '/api/secrets/{secret_id}';
};

export type DeleteCustomSecretApiSecretsSecretIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteCustomSecretApiSecretsSecretIdDeleteError = DeleteCustomSecretApiSecretsSecretIdDeleteErrors[keyof DeleteCustomSecretApiSecretsSecretIdDeleteErrors];

export type DeleteCustomSecretApiSecretsSecretIdDeleteResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type UpdateCustomSecretApiSecretsSecretIdPutData = {
    body: CustomSecretWithoutValueModel;
    path: {
        /**
         * Secret Id
         */
        secret_id: string;
    };
    query?: never;
    url: '/api/secrets/{secret_id}';
};

export type UpdateCustomSecretApiSecretsSecretIdPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateCustomSecretApiSecretsSecretIdPutError = UpdateCustomSecretApiSecretsSecretIdPutErrors[keyof UpdateCustomSecretApiSecretsSecretIdPutErrors];

export type UpdateCustomSecretApiSecretsSecretIdPutResponses = {
    /**
     * Response Update Custom Secret Api Secrets  Secret Id  Put
     * Successful Response
     */
    200: {
        [key: string]: string;
    };
};

export type UpdateCustomSecretApiSecretsSecretIdPutResponse = UpdateCustomSecretApiSecretsSecretIdPutResponses[keyof UpdateCustomSecretApiSecretsSecretIdPutResponses];

export type GetUserRepositoriesApiUserRepositoriesGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Sort
         */
        sort?: string;
    };
    url: '/api/user/repositories';
};

export type GetUserRepositoriesApiUserRepositoriesGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetUserRepositoriesApiUserRepositoriesGetError = GetUserRepositoriesApiUserRepositoriesGetErrors[keyof GetUserRepositoriesApiUserRepositoriesGetErrors];

export type GetUserRepositoriesApiUserRepositoriesGetResponses = {
    /**
     * Response Get User Repositories Api User Repositories Get
     * Successful Response
     */
    200: Array<Repository>;
};

export type GetUserRepositoriesApiUserRepositoriesGetResponse = GetUserRepositoriesApiUserRepositoriesGetResponses[keyof GetUserRepositoriesApiUserRepositoriesGetResponses];

export type GetUserApiUserInfoGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/user/info';
};

export type GetUserApiUserInfoGetResponses = {
    /**
     * Successful Response
     */
    200: User;
};

export type GetUserApiUserInfoGetResponse = GetUserApiUserInfoGetResponses[keyof GetUserApiUserInfoGetResponses];

export type SearchRepositoriesApiUserSearchRepositoriesGetData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Query
         */
        query: string;
        /**
         * Per Page
         */
        per_page?: number;
        /**
         * Sort
         */
        sort?: string;
        /**
         * Order
         */
        order?: string;
    };
    url: '/api/user/search/repositories';
};

export type SearchRepositoriesApiUserSearchRepositoriesGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SearchRepositoriesApiUserSearchRepositoriesGetError = SearchRepositoriesApiUserSearchRepositoriesGetErrors[keyof SearchRepositoriesApiUserSearchRepositoriesGetErrors];

export type SearchRepositoriesApiUserSearchRepositoriesGetResponses = {
    /**
     * Response Search Repositories Api User Search Repositories Get
     * Successful Response
     */
    200: Array<Repository>;
};

export type SearchRepositoriesApiUserSearchRepositoriesGetResponse = SearchRepositoriesApiUserSearchRepositoriesGetResponses[keyof SearchRepositoriesApiUserSearchRepositoriesGetResponses];

export type GetSuggestedTasksApiUserSuggestedTasksGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/user/suggested-tasks';
};

export type GetSuggestedTasksApiUserSuggestedTasksGetResponses = {
    /**
     * Response Get Suggested Tasks Api User Suggested Tasks Get
     * Successful Response
     */
    200: Array<SuggestedTask>;
};

export type GetSuggestedTasksApiUserSuggestedTasksGetResponse = GetSuggestedTasksApiUserSuggestedTasksGetResponses[keyof GetSuggestedTasksApiUserSuggestedTasksGetResponses];

export type GetRepositoryBranchesApiUserRepositoryBranchesGetData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Repository
         */
        repository: string;
    };
    url: '/api/user/repository/branches';
};

export type GetRepositoryBranchesApiUserRepositoryBranchesGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetRepositoryBranchesApiUserRepositoryBranchesGetError = GetRepositoryBranchesApiUserRepositoryBranchesGetErrors[keyof GetRepositoryBranchesApiUserRepositoryBranchesGetErrors];

export type GetRepositoryBranchesApiUserRepositoryBranchesGetResponses = {
    /**
     * Response Get Repository Branches Api User Repository Branches Get
     * Successful Response
     */
    200: Array<Branch>;
};

export type GetRepositoryBranchesApiUserRepositoryBranchesGetResponse = GetRepositoryBranchesApiUserRepositoryBranchesGetResponses[keyof GetRepositoryBranchesApiUserRepositoryBranchesGetResponses];

export type GetTrajectoryApiConversationsConversationIdTrajectoryGetData = {
    body?: never;
    path: {
        /**
         * Conversation Id
         */
        conversation_id: string;
    };
    query?: never;
    url: '/api/conversations/{conversation_id}/trajectory';
};

export type GetTrajectoryApiConversationsConversationIdTrajectoryGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetTrajectoryApiConversationsConversationIdTrajectoryGetError = GetTrajectoryApiConversationsConversationIdTrajectoryGetErrors[keyof GetTrajectoryApiConversationsConversationIdTrajectoryGetErrors];

export type GetTrajectoryApiConversationsConversationIdTrajectoryGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type AliveAliveGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/alive';
};

export type AliveAliveGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type HealthHealthGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type HealthHealthGetResponses = {
    /**
     * Response Health Health Get
     * Successful Response
     */
    200: string;
};

export type HealthHealthGetResponse = HealthHealthGetResponses[keyof HealthHealthGetResponses];

export type GetServerInfoServerInfoGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/server_info';
};

export type GetServerInfoServerInfoGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ClientOptions = {
    baseUrl: 'http://localhost:3000' | (string & {});
};